---
- hosts: apic
  connection: local
  gather_facts: False
  ignore_errors: yes

  vars:
    contents: "{{ lookup('file', './bd-list.txt') }}"
    lines: "{{ contents.split('\n') }}"
    login_info: &login_info
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: false
    #####
    tenant: "TN-ANDRISKA-IAC"
    l3out:  "L3-NEW"
    #####
  tasks:
    - name: Bind Bridge Domain to L3 Out
      cisco.aci.aci_bd_to_l3out:
        <<: *login_info
        bd:                     "{{ item.split(',')[0] }}"
        l3out:                  "{{ l3out }}"
        tenant:                 "{{ tenant }}"
        state:                  present
      with_items:
        - "{{ lines }}"      